version = 1

[[annotations]]
path = ["**"]
precedence = "closest"
SPDX-FileCopyrightText = "2026 Jay Jones"
SPDX-License-Identifier = "PolyForm-Noncommercial-1.0.0"

# Unmodified (or trivially modified) assets from Apple's File Provider sample
[[annotations]]
path = [
  "Action/Base.lproj/AuthenticationViewController.xib",
  "Action/Base.lproj/ConflictViewController.xib",
  "Action/icon.icns",
  "Extension/Info.plist",
  "Server/Info.plist",
  "Provider/Provider.xcassets/basket.symbolset/**",
  "VaultSync/MacApp.xcassets/pictureBadge.iconset/**",
  "VaultSync/RemoveDomainWindow.xib",
]
precedence = "override"
SPDX-FileCopyrightText = "2024 Apple Inc."
SPDX-License-Identifier = "MIT"
